ERROR - 2021-09-24 08:21:19 --> Table 'gull.users' doesn't exist
CRITICAL - 2021-09-24 08:21:19 --> Table 'gull.users' doesn't exist
#0 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(329): mysqli->query('SELECT *\nFROM `...')
#1 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1881): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Model.php(153): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\BaseModel.php(538): CodeIgniter\Model->doFind(true, '2')
#6 C:\xamm\htdocs\pkl\vendor\myth\auth\src\Authentication\AuthenticationBase.php(137): CodeIgniter\BaseModel->find('2')
#7 C:\xamm\htdocs\pkl\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(70): Myth\Auth\Authentication\AuthenticationBase->isLoggedIn()
#8 C:\xamm\htdocs\pkl\vendor\myth\auth\src\Controllers\AuthController.php(46): Myth\Auth\Authentication\LocalAuthenticator->check()
#9 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(928): Myth\Auth\Controllers\AuthController->login()
#10 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#11 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xamm\htdocs\pkl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 {main}
ERROR - 2021-09-24 08:21:31 --> Table 'gull.users' doesn't exist
CRITICAL - 2021-09-24 08:21:31 --> Table 'gull.users' doesn't exist
#0 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(329): mysqli->query('SELECT *\nFROM `...')
#1 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1881): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Model.php(153): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\BaseModel.php(538): CodeIgniter\Model->doFind(true, '2')
#6 C:\xamm\htdocs\pkl\vendor\myth\auth\src\Authentication\AuthenticationBase.php(137): CodeIgniter\BaseModel->find('2')
#7 C:\xamm\htdocs\pkl\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(70): Myth\Auth\Authentication\AuthenticationBase->isLoggedIn()
#8 C:\xamm\htdocs\pkl\vendor\myth\auth\src\Helpers\auth_helper.php(14): Myth\Auth\Authentication\LocalAuthenticator->check()
#9 C:\xamm\htdocs\pkl\app\Views\template\administrator.php(157): logged_in()
#10 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\View\View.php(230): include('C:\\xamm\\htdocs\\...')
#11 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\View\View.php(232): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#12 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\View\View.php(246): CodeIgniter\View\View->render('template/admini...', Array, true)
#13 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Common.php(1271): CodeIgniter\View\View->render('pages/dashboard', Array, true)
#14 C:\xamm\htdocs\pkl\app\Controllers\Home.php(40): view('pages/dashboard', Array)
#15 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\Home->index()
#16 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#17 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#18 C:\xamm\htdocs\pkl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#19 {main}
ERROR - 2021-09-24 08:22:27 --> Table 'gull.users' doesn't exist
CRITICAL - 2021-09-24 08:22:27 --> Table 'gull.users' doesn't exist
#0 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(329): mysqli->query('SELECT *\nFROM `...')
#1 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1881): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Model.php(153): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\BaseModel.php(538): CodeIgniter\Model->doFind(true, '2')
#6 C:\xamm\htdocs\pkl\vendor\myth\auth\src\Authentication\AuthenticationBase.php(137): CodeIgniter\BaseModel->find('2')
#7 C:\xamm\htdocs\pkl\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(70): Myth\Auth\Authentication\AuthenticationBase->isLoggedIn()
#8 C:\xamm\htdocs\pkl\vendor\myth\auth\src\Helpers\auth_helper.php(14): Myth\Auth\Authentication\LocalAuthenticator->check()
#9 C:\xamm\htdocs\pkl\app\Views\template\administrator.php(157): logged_in()
#10 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\View\View.php(230): include('C:\\xamm\\htdocs\\...')
#11 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\View\View.php(232): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#12 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\View\View.php(246): CodeIgniter\View\View->render('template/admini...', Array, true)
#13 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Common.php(1271): CodeIgniter\View\View->render('pages/dashboard', Array, true)
#14 C:\xamm\htdocs\pkl\app\Controllers\Home.php(40): view('pages/dashboard', Array)
#15 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\Home->index()
#16 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#17 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#18 C:\xamm\htdocs\pkl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#19 {main}
ERROR - 2021-09-24 08:22:39 --> Table 'gull.users' doesn't exist
CRITICAL - 2021-09-24 08:22:39 --> Table 'gull.users' doesn't exist
#0 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(329): mysqli->query('SELECT *\nFROM `...')
#1 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1881): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Model.php(153): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\BaseModel.php(538): CodeIgniter\Model->doFind(true, '2')
#6 C:\xamm\htdocs\pkl\vendor\myth\auth\src\Authentication\AuthenticationBase.php(137): CodeIgniter\BaseModel->find('2')
#7 C:\xamm\htdocs\pkl\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(70): Myth\Auth\Authentication\AuthenticationBase->isLoggedIn()
#8 C:\xamm\htdocs\pkl\vendor\myth\auth\src\Helpers\auth_helper.php(14): Myth\Auth\Authentication\LocalAuthenticator->check()
#9 C:\xamm\htdocs\pkl\app\Views\template\administrator.php(157): logged_in()
#10 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\View\View.php(230): include('C:\\xamm\\htdocs\\...')
#11 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\View\View.php(232): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#12 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\View\View.php(246): CodeIgniter\View\View->render('template/admini...', Array, true)
#13 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Common.php(1271): CodeIgniter\View\View->render('pages/dashboard', Array, true)
#14 C:\xamm\htdocs\pkl\app\Controllers\Home.php(40): view('pages/dashboard', Array)
#15 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\Home->index()
#16 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#17 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#18 C:\xamm\htdocs\pkl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#19 {main}
ERROR - 2021-09-24 08:23:33 --> Table 'gull.users' doesn't exist
CRITICAL - 2021-09-24 08:23:33 --> Table 'gull.users' doesn't exist
#0 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(329): mysqli->query('SELECT *\nFROM `...')
#1 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1881): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Model.php(153): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\BaseModel.php(538): CodeIgniter\Model->doFind(true, '2')
#6 C:\xamm\htdocs\pkl\vendor\myth\auth\src\Authentication\AuthenticationBase.php(137): CodeIgniter\BaseModel->find('2')
#7 C:\xamm\htdocs\pkl\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(70): Myth\Auth\Authentication\AuthenticationBase->isLoggedIn()
#8 C:\xamm\htdocs\pkl\vendor\myth\auth\src\Helpers\auth_helper.php(14): Myth\Auth\Authentication\LocalAuthenticator->check()
#9 C:\xamm\htdocs\pkl\app\Views\template\administrator.php(157): logged_in()
#10 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\View\View.php(230): include('C:\\xamm\\htdocs\\...')
#11 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\View\View.php(232): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#12 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\View\View.php(246): CodeIgniter\View\View->render('template/admini...', Array, true)
#13 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Common.php(1271): CodeIgniter\View\View->render('pages/dashboard', Array, true)
#14 C:\xamm\htdocs\pkl\app\Controllers\Home.php(40): view('pages/dashboard', Array)
#15 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\Home->index()
#16 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#17 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#18 C:\xamm\htdocs\pkl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#19 {main}
ERROR - 2021-09-24 08:27:25 --> Table 'gull.users' doesn't exist
CRITICAL - 2021-09-24 08:27:25 --> Table 'gull.users' doesn't exist
#0 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(329): mysqli->query('SELECT *\nFROM `...')
#1 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1881): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Model.php(153): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\BaseModel.php(538): CodeIgniter\Model->doFind(true, '2')
#6 C:\xamm\htdocs\pkl\vendor\myth\auth\src\Authentication\AuthenticationBase.php(137): CodeIgniter\BaseModel->find('2')
#7 C:\xamm\htdocs\pkl\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(70): Myth\Auth\Authentication\AuthenticationBase->isLoggedIn()
#8 C:\xamm\htdocs\pkl\vendor\myth\auth\src\Helpers\auth_helper.php(14): Myth\Auth\Authentication\LocalAuthenticator->check()
#9 C:\xamm\htdocs\pkl\app\Views\template\administrator.php(157): logged_in()
#10 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\View\View.php(230): include('C:\\xamm\\htdocs\\...')
#11 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\View\View.php(232): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#12 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\View\View.php(246): CodeIgniter\View\View->render('template/admini...', Array, true)
#13 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Common.php(1271): CodeIgniter\View\View->render('pages/dashboard', Array, true)
#14 C:\xamm\htdocs\pkl\app\Controllers\Home.php(40): view('pages/dashboard', Array)
#15 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\Home->index()
#16 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#17 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#18 C:\xamm\htdocs\pkl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#19 {main}
CRITICAL - 2021-09-24 08:29:21 --> Call to undefined function logged_in()
#0 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\View\View.php(230): include()
#1 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\View\View.php(232): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\View\View.php(246): CodeIgniter\View\View->render('template/admini...', Array, true)
#3 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Common.php(1271): CodeIgniter\View\View->render('pages/dashboard', Array, true)
#4 C:\xamm\htdocs\pkl\app\Controllers\Home.php(40): view('pages/dashboard', Array)
#5 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\Home->index()
#6 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xamm\htdocs\pkl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-09-24 08:48:25 --> Invalid file: /user/create.php
#0 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\View\View.php(213): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('/user/create.ph...')
#1 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\View\View.php(487): CodeIgniter\View\View->render('/user/create', NULL, true)
#2 C:\xamm\htdocs\pkl\app\Views\user\tabel.php(34): CodeIgniter\View\View->include('/user/create')
#3 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\View\View.php(230): include('C:\\xamm\\htdocs\\...')
#4 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\View\View.php(232): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#5 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Common.php(1271): CodeIgniter\View\View->render('user/tabel', Array, true)
#6 C:\xamm\htdocs\pkl\app\Controllers\User.php(18): view('user/tabel')
#7 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\User->index()
#8 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#9 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xamm\htdocs\pkl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2021-09-24 08:50:42 --> Undefined index: client_id
#0 C:\xamm\htdocs\pkl\app\Controllers\User.php(25): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index...', 'C:\\xamm\\htdocs\\...', 25, Array)
#1 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\User->dt_users()
#2 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#3 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xamm\htdocs\pkl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-09-24 09:16:18 --> Class 'Myth\Auth\Authentication\Passwords\ValidationRules' not found
#0 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Validation\Validation.php(118): CodeIgniter\Validation\Validation->loadRuleSets()
#1 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Controller.php(183): CodeIgniter\Validation\Validation->run()
#2 C:\xamm\htdocs\pkl\app\Controllers\User.php(35): CodeIgniter\Controller->validate(Array)
#3 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\User->validation()
#4 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#5 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xamm\htdocs\pkl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2021-09-24 09:16:20 --> Class 'Myth\Auth\Authentication\Passwords\ValidationRules' not found
#0 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Validation\Validation.php(118): CodeIgniter\Validation\Validation->loadRuleSets()
#1 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Controller.php(183): CodeIgniter\Validation\Validation->run()
#2 C:\xamm\htdocs\pkl\app\Controllers\User.php(35): CodeIgniter\Controller->validate(Array)
#3 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\User->validation()
#4 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#5 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xamm\htdocs\pkl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2021-09-24 09:16:21 --> Class 'Myth\Auth\Authentication\Passwords\ValidationRules' not found
#0 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Validation\Validation.php(118): CodeIgniter\Validation\Validation->loadRuleSets()
#1 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Controller.php(183): CodeIgniter\Validation\Validation->run()
#2 C:\xamm\htdocs\pkl\app\Controllers\User.php(35): CodeIgniter\Controller->validate(Array)
#3 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\User->validation()
#4 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#5 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xamm\htdocs\pkl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2021-09-24 09:16:21 --> Class 'Myth\Auth\Authentication\Passwords\ValidationRules' not found
#0 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Validation\Validation.php(118): CodeIgniter\Validation\Validation->loadRuleSets()
#1 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Controller.php(183): CodeIgniter\Validation\Validation->run()
#2 C:\xamm\htdocs\pkl\app\Controllers\User.php(35): CodeIgniter\Controller->validate(Array)
#3 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\User->validation()
#4 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#5 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xamm\htdocs\pkl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2021-09-24 09:16:21 --> Class 'Myth\Auth\Authentication\Passwords\ValidationRules' not found
#0 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Validation\Validation.php(118): CodeIgniter\Validation\Validation->loadRuleSets()
#1 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Controller.php(183): CodeIgniter\Validation\Validation->run()
#2 C:\xamm\htdocs\pkl\app\Controllers\User.php(35): CodeIgniter\Controller->validate(Array)
#3 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\User->validation()
#4 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#5 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xamm\htdocs\pkl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2021-09-24 09:16:21 --> Class 'Myth\Auth\Authentication\Passwords\ValidationRules' not found
#0 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Validation\Validation.php(118): CodeIgniter\Validation\Validation->loadRuleSets()
#1 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Controller.php(183): CodeIgniter\Validation\Validation->run()
#2 C:\xamm\htdocs\pkl\app\Controllers\User.php(35): CodeIgniter\Controller->validate(Array)
#3 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\User->validation()
#4 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#5 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xamm\htdocs\pkl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2021-09-24 09:16:22 --> Class 'Myth\Auth\Authentication\Passwords\ValidationRules' not found
#0 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Validation\Validation.php(118): CodeIgniter\Validation\Validation->loadRuleSets()
#1 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Controller.php(183): CodeIgniter\Validation\Validation->run()
#2 C:\xamm\htdocs\pkl\app\Controllers\User.php(35): CodeIgniter\Controller->validate(Array)
#3 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\User->validation()
#4 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#5 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xamm\htdocs\pkl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2021-09-24 09:16:22 --> Class 'Myth\Auth\Authentication\Passwords\ValidationRules' not found
#0 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Validation\Validation.php(118): CodeIgniter\Validation\Validation->loadRuleSets()
#1 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Controller.php(183): CodeIgniter\Validation\Validation->run()
#2 C:\xamm\htdocs\pkl\app\Controllers\User.php(35): CodeIgniter\Controller->validate(Array)
#3 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\User->validation()
#4 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#5 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xamm\htdocs\pkl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2021-09-24 09:18:05 --> Class 'Myth\Auth\Authentication\Passwords\ValidationRules' not found
#0 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Validation\Validation.php(118): CodeIgniter\Validation\Validation->loadRuleSets()
#1 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Controller.php(183): CodeIgniter\Validation\Validation->run()
#2 C:\xamm\htdocs\pkl\app\Controllers\User.php(35): CodeIgniter\Controller->validate(Array)
#3 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\User->validation()
#4 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#5 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xamm\htdocs\pkl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2021-09-24 09:18:06 --> Class 'Myth\Auth\Authentication\Passwords\ValidationRules' not found
#0 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Validation\Validation.php(118): CodeIgniter\Validation\Validation->loadRuleSets()
#1 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Controller.php(183): CodeIgniter\Validation\Validation->run()
#2 C:\xamm\htdocs\pkl\app\Controllers\User.php(35): CodeIgniter\Controller->validate(Array)
#3 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\User->validation()
#4 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#5 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xamm\htdocs\pkl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2021-09-24 09:18:07 --> Class 'Myth\Auth\Authentication\Passwords\ValidationRules' not found
#0 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Validation\Validation.php(118): CodeIgniter\Validation\Validation->loadRuleSets()
#1 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Controller.php(183): CodeIgniter\Validation\Validation->run()
#2 C:\xamm\htdocs\pkl\app\Controllers\User.php(35): CodeIgniter\Controller->validate(Array)
#3 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\User->validation()
#4 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#5 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xamm\htdocs\pkl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2021-09-24 09:18:09 --> Class 'Myth\Auth\Authentication\Passwords\ValidationRules' not found
#0 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Validation\Validation.php(118): CodeIgniter\Validation\Validation->loadRuleSets()
#1 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Controller.php(183): CodeIgniter\Validation\Validation->run()
#2 C:\xamm\htdocs\pkl\app\Controllers\User.php(35): CodeIgniter\Controller->validate(Array)
#3 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\User->validation()
#4 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#5 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xamm\htdocs\pkl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2021-09-24 09:18:10 --> Class 'Myth\Auth\Authentication\Passwords\ValidationRules' not found
#0 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Validation\Validation.php(118): CodeIgniter\Validation\Validation->loadRuleSets()
#1 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Controller.php(183): CodeIgniter\Validation\Validation->run()
#2 C:\xamm\htdocs\pkl\app\Controllers\User.php(35): CodeIgniter\Controller->validate(Array)
#3 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\User->validation()
#4 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#5 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xamm\htdocs\pkl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2021-09-24 09:18:11 --> Class 'Myth\Auth\Authentication\Passwords\ValidationRules' not found
#0 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Validation\Validation.php(118): CodeIgniter\Validation\Validation->loadRuleSets()
#1 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Controller.php(183): CodeIgniter\Validation\Validation->run()
#2 C:\xamm\htdocs\pkl\app\Controllers\User.php(35): CodeIgniter\Controller->validate(Array)
#3 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\User->validation()
#4 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#5 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xamm\htdocs\pkl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2021-09-24 09:18:11 --> Class 'Myth\Auth\Authentication\Passwords\ValidationRules' not found
#0 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Validation\Validation.php(118): CodeIgniter\Validation\Validation->loadRuleSets()
#1 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Controller.php(183): CodeIgniter\Validation\Validation->run()
#2 C:\xamm\htdocs\pkl\app\Controllers\User.php(35): CodeIgniter\Controller->validate(Array)
#3 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\User->validation()
#4 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#5 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xamm\htdocs\pkl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2021-09-24 09:18:11 --> Class 'Myth\Auth\Authentication\Passwords\ValidationRules' not found
#0 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Validation\Validation.php(118): CodeIgniter\Validation\Validation->loadRuleSets()
#1 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Controller.php(183): CodeIgniter\Validation\Validation->run()
#2 C:\xamm\htdocs\pkl\app\Controllers\User.php(35): CodeIgniter\Controller->validate(Array)
#3 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\User->validation()
#4 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#5 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xamm\htdocs\pkl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2021-09-24 09:20:26 --> Class 'Myth\Auth\Authentication\Passwords\ValidationRules' not found
#0 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Validation\Validation.php(118): CodeIgniter\Validation\Validation->loadRuleSets()
#1 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Controller.php(183): CodeIgniter\Validation\Validation->run()
#2 C:\xamm\htdocs\pkl\app\Controllers\User.php(35): CodeIgniter\Controller->validate(Array)
#3 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\User->validation()
#4 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#5 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xamm\htdocs\pkl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2021-09-24 09:20:27 --> Class 'Myth\Auth\Authentication\Passwords\ValidationRules' not found
#0 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Validation\Validation.php(118): CodeIgniter\Validation\Validation->loadRuleSets()
#1 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Controller.php(183): CodeIgniter\Validation\Validation->run()
#2 C:\xamm\htdocs\pkl\app\Controllers\User.php(35): CodeIgniter\Controller->validate(Array)
#3 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\User->validation()
#4 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#5 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xamm\htdocs\pkl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2021-09-24 09:21:36 --> Class 'Myth\Auth\Authentication\Passwords\ValidationRules' not found
#0 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Validation\Validation.php(118): CodeIgniter\Validation\Validation->loadRuleSets()
#1 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Controller.php(183): CodeIgniter\Validation\Validation->run()
#2 C:\xamm\htdocs\pkl\app\Controllers\User.php(35): CodeIgniter\Controller->validate(Array)
#3 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\User->validation()
#4 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#5 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xamm\htdocs\pkl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2021-09-24 09:23:30 --> Class 'Myth\Auth\Authentication\Passwords\ValidationRules' not found
#0 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Validation\Validation.php(118): CodeIgniter\Validation\Validation->loadRuleSets()
#1 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Controller.php(183): CodeIgniter\Validation\Validation->run()
#2 C:\xamm\htdocs\pkl\app\Controllers\User.php(35): CodeIgniter\Controller->validate(Array)
#3 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\User->validation()
#4 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#5 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xamm\htdocs\pkl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2021-09-24 09:27:00 --> Class 'Myth\Auth\Authentication\Passwords\ValidationRules' not found
#0 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Validation\Validation.php(118): CodeIgniter\Validation\Validation->loadRuleSets()
#1 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Controller.php(183): CodeIgniter\Validation\Validation->run()
#2 C:\xamm\htdocs\pkl\app\Controllers\User.php(35): CodeIgniter\Controller->validate(Array)
#3 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\User->validation()
#4 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#5 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xamm\htdocs\pkl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2021-09-24 09:28:53 --> Class 'Myth\Auth\Authentication\Passwords\ValidationRules' not found
#0 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Validation\Validation.php(118): CodeIgniter\Validation\Validation->loadRuleSets()
#1 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Controller.php(183): CodeIgniter\Validation\Validation->run()
#2 C:\xamm\htdocs\pkl\app\Controllers\User.php(35): CodeIgniter\Controller->validate(Array)
#3 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\User->validation()
#4 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#5 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xamm\htdocs\pkl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2021-09-24 09:29:08 --> Class 'Myth\Auth\Authentication\Passwords\ValidationRules' not found
#0 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Validation\Validation.php(118): CodeIgniter\Validation\Validation->loadRuleSets()
#1 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Controller.php(183): CodeIgniter\Validation\Validation->run()
#2 C:\xamm\htdocs\pkl\app\Controllers\User.php(35): CodeIgniter\Controller->validate(Array)
#3 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\User->validation()
#4 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#5 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xamm\htdocs\pkl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2021-09-24 09:32:38 --> Class 'Myth\Auth\Authentication\Passwords\ValidationRules' not found
#0 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Validation\Validation.php(118): CodeIgniter\Validation\Validation->loadRuleSets()
#1 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Controller.php(183): CodeIgniter\Validation\Validation->run()
#2 C:\xamm\htdocs\pkl\app\Controllers\User.php(36): CodeIgniter\Controller->validate(Array)
#3 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\User->validation()
#4 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#5 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xamm\htdocs\pkl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2021-09-24 09:35:09 --> Class 'Myth\Auth\Authentication\Passwords\ValidationRules' not found
#0 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Validation\Validation.php(118): CodeIgniter\Validation\Validation->loadRuleSets()
#1 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Controller.php(183): CodeIgniter\Validation\Validation->run()
#2 C:\xamm\htdocs\pkl\app\Controllers\Client.php(36): CodeIgniter\Controller->validate(Array)
#3 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\client->validation()
#4 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\client))
#5 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xamm\htdocs\pkl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2021-09-24 09:36:42 --> Class 'Myth\Auth\Authentication\Passwords\ValidationRules' not found
#0 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Validation\Validation.php(118): CodeIgniter\Validation\Validation->loadRuleSets()
#1 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Controller.php(183): CodeIgniter\Validation\Validation->run()
#2 C:\xamm\htdocs\pkl\app\Controllers\Client.php(36): CodeIgniter\Controller->validate(Array)
#3 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\client->validation()
#4 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\client))
#5 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xamm\htdocs\pkl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2021-09-24 09:36:59 --> Class 'Myth\Auth\Authentication\Passwords\ValidationRules' not found
#0 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Validation\Validation.php(118): CodeIgniter\Validation\Validation->loadRuleSets()
#1 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Controller.php(183): CodeIgniter\Validation\Validation->run()
#2 C:\xamm\htdocs\pkl\app\Controllers\Client.php(36): CodeIgniter\Controller->validate(Array)
#3 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\client->validation()
#4 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\client))
#5 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xamm\htdocs\pkl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2021-09-24 09:38:28 --> Class 'Myth\Auth\Authentication\Passwords\ValidationRules' not found
#0 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Validation\Validation.php(118): CodeIgniter\Validation\Validation->loadRuleSets()
#1 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Controller.php(183): CodeIgniter\Validation\Validation->run()
#2 C:\xamm\htdocs\pkl\app\Controllers\Client.php(36): CodeIgniter\Controller->validate(Array)
#3 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\client->validation()
#4 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\client))
#5 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xamm\htdocs\pkl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2021-09-24 09:38:38 --> Class 'Myth\Auth\Authentication\Passwords\ValidationRules' not found
#0 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Validation\Validation.php(118): CodeIgniter\Validation\Validation->loadRuleSets()
#1 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Controller.php(183): CodeIgniter\Validation\Validation->run()
#2 C:\xamm\htdocs\pkl\app\Controllers\Client.php(36): CodeIgniter\Controller->validate(Array)
#3 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\client->validation()
#4 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\client))
#5 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xamm\htdocs\pkl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2021-09-24 09:38:54 --> Class 'Myth\Auth\Authentication\Passwords\ValidationRules' not found
#0 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Validation\Validation.php(118): CodeIgniter\Validation\Validation->loadRuleSets()
#1 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Controller.php(183): CodeIgniter\Validation\Validation->run()
#2 C:\xamm\htdocs\pkl\app\Controllers\Client.php(91): CodeIgniter\Controller->validate(Array)
#3 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\client->hupdate()
#4 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\client))
#5 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xamm\htdocs\pkl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
ERROR - 2021-09-24 09:53:37 --> Unknown column 'created_at' in 'field list'
CRITICAL - 2021-09-24 09:53:37 --> Unknown column 'created_at' in 'field list'
#0 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(329): mysqli->query('INSERT INTO `us...')
#1 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2277): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Model.php(259): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\BaseModel.php(774): CodeIgniter\Model->doInsert(Array)
#6 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Model.php(686): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\BaseModel.php(687): CodeIgniter\Model->insert(Array, false)
#8 C:\xamm\htdocs\pkl\app\Controllers\User.php(72): CodeIgniter\BaseModel->save(Array)
#9 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\User->validation()
#10 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#11 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xamm\htdocs\pkl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 {main}
ERROR - 2021-09-24 09:55:27 --> Unknown column 'created_at' in 'field list'
CRITICAL - 2021-09-24 09:55:27 --> Unknown column 'created_at' in 'field list'
#0 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(329): mysqli->query('INSERT INTO `us...')
#1 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2277): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Model.php(259): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\BaseModel.php(774): CodeIgniter\Model->doInsert(Array)
#6 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Model.php(686): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\BaseModel.php(687): CodeIgniter\Model->insert(Array, false)
#8 C:\xamm\htdocs\pkl\app\Controllers\User.php(72): CodeIgniter\BaseModel->save(Array)
#9 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\User->validation()
#10 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#11 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xamm\htdocs\pkl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 {main}
ERROR - 2021-09-24 09:55:40 --> Unknown column 'created_at' in 'field list'
CRITICAL - 2021-09-24 09:55:40 --> Unknown column 'created_at' in 'field list'
#0 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(329): mysqli->query('INSERT INTO `us...')
#1 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2277): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Model.php(259): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\BaseModel.php(774): CodeIgniter\Model->doInsert(Array)
#6 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Model.php(686): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\BaseModel.php(687): CodeIgniter\Model->insert(Array, false)
#8 C:\xamm\htdocs\pkl\app\Controllers\User.php(72): CodeIgniter\BaseModel->save(Array)
#9 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\User->validation()
#10 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#11 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xamm\htdocs\pkl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 {main}
ERROR - 2021-09-24 10:01:01 --> Unknown column 'created_at' in 'field list'
CRITICAL - 2021-09-24 10:01:01 --> Unknown column 'created_at' in 'field list'
#0 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(329): mysqli->query('INSERT INTO `us...')
#1 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2277): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Model.php(259): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\BaseModel.php(774): CodeIgniter\Model->doInsert(Array)
#6 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Model.php(686): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\BaseModel.php(687): CodeIgniter\Model->insert(Array, false)
#8 C:\xamm\htdocs\pkl\app\Controllers\User.php(72): CodeIgniter\BaseModel->save(Array)
#9 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\User->validation()
#10 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#11 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xamm\htdocs\pkl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 {main}
ERROR - 2021-09-24 10:05:46 --> Unknown column 'created_at' in 'field list'
CRITICAL - 2021-09-24 10:05:46 --> Unknown column 'created_at' in 'field list'
#0 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(329): mysqli->query('INSERT INTO `us...')
#1 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2277): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Model.php(259): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\BaseModel.php(774): CodeIgniter\Model->doInsert(Array)
#6 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Model.php(686): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\BaseModel.php(687): CodeIgniter\Model->insert(Array, false)
#8 C:\xamm\htdocs\pkl\app\Controllers\User.php(72): CodeIgniter\BaseModel->save(Array)
#9 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\User->validation()
#10 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#11 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xamm\htdocs\pkl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 {main}
ERROR - 2021-09-24 10:06:29 --> Unknown column 'created_at' in 'field list'
CRITICAL - 2021-09-24 10:06:29 --> Unknown column 'created_at' in 'field list'
#0 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(329): mysqli->query('INSERT INTO `us...')
#1 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2277): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Model.php(259): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\BaseModel.php(774): CodeIgniter\Model->doInsert(Array)
#6 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Model.php(686): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\BaseModel.php(687): CodeIgniter\Model->insert(Array, false)
#8 C:\xamm\htdocs\pkl\app\Controllers\User.php(72): CodeIgniter\BaseModel->save(Array)
#9 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\User->validation()
#10 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#11 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xamm\htdocs\pkl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 {main}
ERROR - 2021-09-24 10:10:27 --> Unknown column 'created_at' in 'field list'
CRITICAL - 2021-09-24 10:10:27 --> Unknown column 'created_at' in 'field list'
#0 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(329): mysqli->query('INSERT INTO `us...')
#1 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2277): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Model.php(259): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\BaseModel.php(774): CodeIgniter\Model->doInsert(Array)
#6 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Model.php(686): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\BaseModel.php(687): CodeIgniter\Model->insert(Array, false)
#8 C:\xamm\htdocs\pkl\app\Controllers\User.php(72): CodeIgniter\BaseModel->save(Array)
#9 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\User->validation()
#10 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#11 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xamm\htdocs\pkl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 {main}
ERROR - 2021-09-24 10:13:48 --> Unknown column 'created_at' in 'field list'
CRITICAL - 2021-09-24 10:13:48 --> Unknown column 'created_at' in 'field list'
#0 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(329): mysqli->query('INSERT INTO `us...')
#1 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2277): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Model.php(259): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\BaseModel.php(774): CodeIgniter\Model->doInsert(Array)
#6 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Model.php(686): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\BaseModel.php(687): CodeIgniter\Model->insert(Array, false)
#8 C:\xamm\htdocs\pkl\app\Controllers\User.php(72): CodeIgniter\BaseModel->save(Array)
#9 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\User->validation()
#10 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#11 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xamm\htdocs\pkl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 {main}
ERROR - 2021-09-24 10:16:48 --> Unknown column 'created_at' in 'field list'
CRITICAL - 2021-09-24 10:16:48 --> Unknown column 'created_at' in 'field list'
#0 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(329): mysqli->query('INSERT INTO `us...')
#1 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2277): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Model.php(259): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\BaseModel.php(774): CodeIgniter\Model->doInsert(Array)
#6 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Model.php(686): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\BaseModel.php(687): CodeIgniter\Model->insert(Array, false)
#8 C:\xamm\htdocs\pkl\app\Controllers\User.php(72): CodeIgniter\BaseModel->save(Array)
#9 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\User->validation()
#10 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#11 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xamm\htdocs\pkl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 {main}
ERROR - 2021-09-24 10:18:11 --> Unknown column 'created_at' in 'field list'
CRITICAL - 2021-09-24 10:18:11 --> Unknown column 'created_at' in 'field list'
#0 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(329): mysqli->query('INSERT INTO `us...')
#1 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2277): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Model.php(259): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\BaseModel.php(774): CodeIgniter\Model->doInsert(Array)
#6 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Model.php(686): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\BaseModel.php(687): CodeIgniter\Model->insert(Array, false)
#8 C:\xamm\htdocs\pkl\app\Controllers\User.php(72): CodeIgniter\BaseModel->save(Array)
#9 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\User->validation()
#10 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#11 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xamm\htdocs\pkl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 {main}
ERROR - 2021-09-24 10:20:59 --> Unknown column 'created_at' in 'field list'
CRITICAL - 2021-09-24 10:20:59 --> Unknown column 'created_at' in 'field list'
#0 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(329): mysqli->query('INSERT INTO `us...')
#1 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2277): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Model.php(259): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\BaseModel.php(774): CodeIgniter\Model->doInsert(Array)
#6 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Model.php(686): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\BaseModel.php(687): CodeIgniter\Model->insert(Array, false)
#8 C:\xamm\htdocs\pkl\app\Controllers\User.php(86): CodeIgniter\BaseModel->save(Array)
#9 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\User->validation()
#10 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#11 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xamm\htdocs\pkl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 {main}
ERROR - 2021-09-24 10:21:37 --> Unknown column 'created_at' in 'field list'
CRITICAL - 2021-09-24 10:21:37 --> Unknown column 'created_at' in 'field list'
#0 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(329): mysqli->query('INSERT INTO `us...')
#1 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2277): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Model.php(259): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\BaseModel.php(774): CodeIgniter\Model->doInsert(Array)
#6 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Model.php(686): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\BaseModel.php(687): CodeIgniter\Model->insert(Array, false)
#8 C:\xamm\htdocs\pkl\app\Controllers\User.php(86): CodeIgniter\BaseModel->save(Array)
#9 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\User->validation()
#10 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#11 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xamm\htdocs\pkl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 {main}
ERROR - 2021-09-24 10:21:39 --> Unknown column 'created_at' in 'field list'
CRITICAL - 2021-09-24 10:21:39 --> Unknown column 'created_at' in 'field list'
#0 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(329): mysqli->query('INSERT INTO `us...')
#1 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2277): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Model.php(259): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\BaseModel.php(774): CodeIgniter\Model->doInsert(Array)
#6 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Model.php(686): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\BaseModel.php(687): CodeIgniter\Model->insert(Array, false)
#8 C:\xamm\htdocs\pkl\app\Controllers\User.php(86): CodeIgniter\BaseModel->save(Array)
#9 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\User->validation()
#10 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#11 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xamm\htdocs\pkl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 {main}
ERROR - 2021-09-24 10:21:40 --> Unknown column 'created_at' in 'field list'
CRITICAL - 2021-09-24 10:21:40 --> Unknown column 'created_at' in 'field list'
#0 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(329): mysqli->query('INSERT INTO `us...')
#1 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2277): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Model.php(259): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\BaseModel.php(774): CodeIgniter\Model->doInsert(Array)
#6 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Model.php(686): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\BaseModel.php(687): CodeIgniter\Model->insert(Array, false)
#8 C:\xamm\htdocs\pkl\app\Controllers\User.php(86): CodeIgniter\BaseModel->save(Array)
#9 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\User->validation()
#10 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#11 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xamm\htdocs\pkl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 {main}
ERROR - 2021-09-24 10:31:00 --> Unknown column 'created_at' in 'field list'
CRITICAL - 2021-09-24 10:31:00 --> Unknown column 'created_at' in 'field list'
#0 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(329): mysqli->query('INSERT INTO `us...')
#1 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2277): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Model.php(259): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\BaseModel.php(774): CodeIgniter\Model->doInsert(Array)
#6 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Model.php(686): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\BaseModel.php(687): CodeIgniter\Model->insert(Array, false)
#8 C:\xamm\htdocs\pkl\app\Controllers\User.php(72): CodeIgniter\BaseModel->save(Array)
#9 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\User->validation()
#10 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#11 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xamm\htdocs\pkl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 {main}
ERROR - 2021-09-24 10:45:28 --> Unknown column 'created_at' in 'field list'
CRITICAL - 2021-09-24 10:45:28 --> Unknown column 'created_at' in 'field list'
#0 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(329): mysqli->query('INSERT INTO `us...')
#1 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2277): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Model.php(259): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\BaseModel.php(774): CodeIgniter\Model->doInsert(Array)
#6 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Model.php(686): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\BaseModel.php(687): CodeIgniter\Model->insert(Array, false)
#8 C:\xamm\htdocs\pkl\app\Controllers\User.php(72): CodeIgniter\BaseModel->save(Array)
#9 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\User->validation()
#10 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#11 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xamm\htdocs\pkl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 {main}
ERROR - 2021-09-24 10:49:38 --> Unknown column 'created_at' in 'field list'
CRITICAL - 2021-09-24 10:49:38 --> Unknown column 'created_at' in 'field list'
#0 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(329): mysqli->query('INSERT INTO `us...')
#1 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2277): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Model.php(259): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\BaseModel.php(774): CodeIgniter\Model->doInsert(Array)
#6 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Model.php(686): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\BaseModel.php(687): CodeIgniter\Model->insert(Array, false)
#8 C:\xamm\htdocs\pkl\app\Controllers\User.php(72): CodeIgniter\BaseModel->save(Array)
#9 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\User->validation()
#10 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#11 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xamm\htdocs\pkl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 {main}
ERROR - 2021-09-24 10:51:31 --> Unknown column 'created_at' in 'field list'
CRITICAL - 2021-09-24 10:51:31 --> Unknown column 'created_at' in 'field list'
#0 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(329): mysqli->query('INSERT INTO `us...')
#1 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2277): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Model.php(259): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\BaseModel.php(774): CodeIgniter\Model->doInsert(Array)
#6 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Model.php(686): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\BaseModel.php(687): CodeIgniter\Model->insert(Array, false)
#8 C:\xamm\htdocs\pkl\app\Controllers\User.php(72): CodeIgniter\BaseModel->save(Array)
#9 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\User->validation()
#10 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#11 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xamm\htdocs\pkl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 {main}
ERROR - 2021-09-24 10:53:28 --> Unknown column 'created_at' in 'field list'
CRITICAL - 2021-09-24 10:53:28 --> Unknown column 'created_at' in 'field list'
#0 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(329): mysqli->query('INSERT INTO `us...')
#1 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2277): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Model.php(259): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\BaseModel.php(774): CodeIgniter\Model->doInsert(Array)
#6 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Model.php(686): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\BaseModel.php(687): CodeIgniter\Model->insert(Array, false)
#8 C:\xamm\htdocs\pkl\app\Controllers\User.php(72): CodeIgniter\BaseModel->save(Array)
#9 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\User->validation()
#10 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#11 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xamm\htdocs\pkl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 {main}
ERROR - 2021-09-24 11:26:16 --> Unknown column 'created_at' in 'field list'
CRITICAL - 2021-09-24 11:26:16 --> Unknown column 'created_at' in 'field list'
#0 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(329): mysqli->query('INSERT INTO `us...')
#1 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2277): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Model.php(259): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\BaseModel.php(774): CodeIgniter\Model->doInsert(Array)
#6 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Model.php(686): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\BaseModel.php(687): CodeIgniter\Model->insert(Array, false)
#8 C:\xamm\htdocs\pkl\app\Controllers\User.php(71): CodeIgniter\BaseModel->save(Array)
#9 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\User->validation()
#10 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#11 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xamm\htdocs\pkl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2021-09-24 11:29:35 --> Call to undefined function App\Controllers\user()
#0 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\client->hupdate()
#1 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\client))
#2 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xamm\htdocs\pkl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2021-09-24 11:29:42 --> Call to undefined function App\Controllers\user()
#0 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\client->hupdate()
#1 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\client))
#2 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xamm\htdocs\pkl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2021-09-24 11:31:28 --> Call to undefined function App\Controllers\user()
#0 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\client->hupdate()
#1 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\client))
#2 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xamm\htdocs\pkl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
ERROR - 2021-09-24 11:38:08 --> Unknown column 'created_at' in 'field list'
CRITICAL - 2021-09-24 11:38:08 --> Unknown column 'created_at' in 'field list'
#0 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(329): mysqli->query('INSERT INTO `us...')
#1 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2277): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Model.php(259): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\BaseModel.php(774): CodeIgniter\Model->doInsert(Array)
#6 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Model.php(686): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\BaseModel.php(687): CodeIgniter\Model->insert(Array, false)
#8 C:\xamm\htdocs\pkl\app\Controllers\User.php(71): CodeIgniter\BaseModel->save(Array)
#9 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\User->validation()
#10 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#11 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xamm\htdocs\pkl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 {main}
ERROR - 2021-09-24 11:41:35 --> Unknown column 'created_at' in 'field list'
CRITICAL - 2021-09-24 11:41:35 --> Unknown column 'created_at' in 'field list'
#0 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(329): mysqli->query('INSERT INTO `us...')
#1 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2277): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Model.php(259): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\BaseModel.php(774): CodeIgniter\Model->doInsert(Array)
#6 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Model.php(686): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\BaseModel.php(687): CodeIgniter\Model->insert(Array, false)
#8 C:\xamm\htdocs\pkl\app\Controllers\User.php(71): CodeIgniter\BaseModel->save(Array)
#9 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\User->validation()
#10 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#11 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xamm\htdocs\pkl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 {main}
ERROR - 2021-09-24 15:27:46 --> Unknown column 'created_at' in 'field list'
CRITICAL - 2021-09-24 15:27:46 --> Unknown column 'created_at' in 'field list'
#0 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(329): mysqli->query('INSERT INTO `us...')
#1 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2277): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Model.php(259): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\BaseModel.php(774): CodeIgniter\Model->doInsert(Array)
#6 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Model.php(686): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\BaseModel.php(687): CodeIgniter\Model->insert(Array, false)
#8 C:\xamm\htdocs\pkl\app\Controllers\User.php(71): CodeIgniter\BaseModel->save(Array)
#9 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\User->validation()
#10 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#11 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xamm\htdocs\pkl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2021-09-24 15:29:46 --> Undefined variable: title
#0 C:\xamm\htdocs\pkl\app\Views\login.php(6): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xamm\\htdocs\\...', 6, Array)
#1 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\View\View.php(230): include('C:\\xamm\\htdocs\\...')
#2 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\View\View.php(232): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\Common.php(1271): CodeIgniter\View\View->render('/login', Array, true)
#4 C:\xamm\htdocs\pkl\app\Controllers\login.php(18): view('/login')
#5 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\login->index()
#6 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login))
#7 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xamm\htdocs\pkl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-09-24 16:25:18 --> Object of class CodeIgniter\HTTP\RedirectResponse could not be converted to string
#0 C:\xamm\htdocs\pkl\app\Controllers\login.php(48): CodeIgniter\Debug\Exceptions->errorHandler(4096, 'Object of class...', 'C:\\xamm\\htdocs\\...', 48, Array)
#1 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\login->auth()
#2 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login))
#3 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xamm\htdocs\pkl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-09-24 16:25:18 --> Object of class CodeIgniter\HTTP\RedirectResponse could not be converted to string
#0 C:\xamm\htdocs\pkl\app\Controllers\login.php(48): CodeIgniter\Debug\Exceptions->errorHandler(4096, 'Object of class...', 'C:\\xamm\\htdocs\\...', 48, Array)
#1 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\login->auth()
#2 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login))
#3 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xamm\htdocs\pkl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-09-24 16:28:03 --> Object of class CodeIgniter\HTTP\RedirectResponse could not be converted to string
#0 C:\xamm\htdocs\pkl\app\Controllers\login.php(48): CodeIgniter\Debug\Exceptions->errorHandler(4096, 'Object of class...', 'C:\\xamm\\htdocs\\...', 48, Array)
#1 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\login->auth()
#2 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login))
#3 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xamm\htdocs\pkl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-09-24 16:28:03 --> Object of class CodeIgniter\HTTP\RedirectResponse could not be converted to string
#0 C:\xamm\htdocs\pkl\app\Controllers\login.php(48): CodeIgniter\Debug\Exceptions->errorHandler(4096, 'Object of class...', 'C:\\xamm\\htdocs\\...', 48, Array)
#1 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\login->auth()
#2 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login))
#3 C:\xamm\htdocs\pkl\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xamm\htdocs\pkl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
